/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.Cargar;
import Funciones.FileChooser;
import static Interfaces.Iniciar.arbolG;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registro = new javax.swing.JButton();
        busquedaNombre = new javax.swing.JButton();
        busquedaTitulo = new javax.swing.JButton();
        mostrarAntepasados = new javax.swing.JButton();
        busquedaGeneraciones = new javax.swing.JButton();
        cargarJSON = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Menú");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 155, -1));

        registro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registro.setText("Ver Registro");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel1.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 257, -1));

        busquedaNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        busquedaNombre.setText("Búsqueda por nombre");
        busquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(busquedaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 257, -1));

        busquedaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        busquedaTitulo.setText("Búsqueda por título");
        busquedaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaTituloActionPerformed(evt);
            }
        });
        jPanel1.add(busquedaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 257, -1));

        mostrarAntepasados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mostrarAntepasados.setText("Mostrar Antepasados");
        mostrarAntepasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarAntepasadosActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarAntepasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 257, -1));

        busquedaGeneraciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        busquedaGeneraciones.setText("Lista de integrantes de una generación");
        busquedaGeneraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaGeneracionesActionPerformed(evt);
            }
        });
        jPanel1.add(busquedaGeneraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 257, -1));

        cargarJSON.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cargarJSON.setText("Cargar JSON");
        cargarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarJSONActionPerformed(evt);
            }
        });
        jPanel1.add(cargarJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 257, -1));

        salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 257, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 407, 429));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // **Botón para salir del sistema*/
        System.out.print("Hasta Luego");
        JOptionPane.showMessageDialog(null, "Hasta Luego");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void busquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaNombreActionPerformed
        // **Botón para ir hasta la pestana de búsqueda por nombre*/
        BuscarPorNombre buscarnombre = new BuscarPorNombre();
        this.dispose();
    }//GEN-LAST:event_busquedaNombreActionPerformed

    private void busquedaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaTituloActionPerformed
        // **Botón para ir hasta la pestana de búsqueda por título*/
        BuscarPorTitulo buscartitulo = new BuscarPorTitulo();
        this.dispose();
    }//GEN-LAST:event_busquedaTituloActionPerformed

    private void mostrarAntepasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarAntepasadosActionPerformed
        // **Botón para ir hasta la pestana de Mostrar Antepasados*/
        MostrarAntepasados antepasados = new MostrarAntepasados();
        this.dispose();
    }//GEN-LAST:event_mostrarAntepasadosActionPerformed

    private void busquedaGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaGeneracionesActionPerformed
        // **Botón para ir hasta la pestana de búsqueda por Generación*/
        BuscarPorGeneraciones buscargeneraciones = new BuscarPorGeneraciones();
        this.dispose();
    }//GEN-LAST:event_busquedaGeneracionesActionPerformed

    private void cargarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarJSONActionPerformed
        
        FileChooser fileChooser = new FileChooser(this);
        String ruta = fileChooser.abrirArchivo();
        
        Cargar cargarArchivoJSON = new Cargar();
        cargarArchivoJSON.cargar(ruta);
        
        if (cargarArchivoJSON.cargaExitosa()) {
            arbolG.destruir();
            arbolG.setArbol(cargarArchivoJSON.getArbol());
            arbolG.setHashTable(cargarArchivoJSON.getHashTable());
            JOptionPane.showMessageDialog(null, "Carga Exitosa");
//            cargarJSON.getArbol().mostrarArbolPorNiveles();
            //System.out.println(cargarJSON.getArbol().obtenerNivelMaximo());
        }else{
            JOptionPane.showMessageDialog(null, "Hay errores en el JSON");
        }
    }//GEN-LAST:event_cargarJSONActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busquedaGeneraciones;
    private javax.swing.JButton busquedaNombre;
    private javax.swing.JButton busquedaTitulo;
    private javax.swing.JButton cargarJSON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarAntepasados;
    private javax.swing.JButton registro;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
